In [29]:

import pandas as pd 

#carrego o arquivo xlss
xls_file = pd.ExcelFile('FormFiltroConsultaVendaSintetica_29_04_2024_10_06_56.xls')

#Escolher a primeira planilha do arquivo 
df = pd.read_excel(xls_file)

#dropa a linha 0 e grava no arquivo original 
df = df.drop(0)

#salvar os dados em csv
df.to_csv('convertido.csv', index=False)
#print(df)

WARNING *** file size (370326) not 512 + multiple of sector size (512)

In [30]:
data = pd.read_csv('convertido.csv')
#data = pd.read_excel('FormFiltroConsultaVendaSintetica_29_04_2024_10_06_56.xls')
limpa = data.drop('Ano', axis=1)
limpa.to_csv('convertido.csv', index=False)
print (limpa)

     Unnamed: 1      Mês  ...  Estoque Atual  Estoque Mínimo
0        2023.0  04/2023  ...            0.0             0.0
1        2023.0  04/2023  ...            0.0             0.0
2        2023.0  04/2023  ...            0.0             0.0
3        2023.0  04/2023  ...            0.0             0.0
4        2023.0  04/2023  ...            0.0             0.0
..          ...      ...  ...            ...             ...
974      2023.0  04/2023  ...            0.0             0.0
975      2023.0  04/2023  ...            0.0             0.0
976      2023.0  04/2023  ...            0.0             0.0
977      2023.0  04/2023  ...            0.0             0.0
978         NaN      NaN  ...            NaN             NaN

[979 rows x 13 columns]

In [31]:
df = pd.read_csv('convertido.csv')
df.rename(columns={'Unnamed: 1': 'Ano'}, inplace = True)
df.to_csv('convertido.csv', index=False)

In [32]:
print (df)

        Ano      Mês  ...  Estoque Atual  Estoque Mínimo
0    2023.0  04/2023  ...            0.0             0.0
1    2023.0  04/2023  ...            0.0             0.0
2    2023.0  04/2023  ...            0.0             0.0
3    2023.0  04/2023  ...            0.0             0.0
4    2023.0  04/2023  ...            0.0             0.0
..      ...      ...  ...            ...             ...
974  2023.0  04/2023  ...            0.0             0.0
975  2023.0  04/2023  ...            0.0             0.0
976  2023.0  04/2023  ...            0.0             0.0
977  2023.0  04/2023  ...            0.0             0.0
978     NaN      NaN  ...            NaN             NaN

[979 rows x 13 columns]

In [35]:
pd.set_option('display.max_columns', None)
print(df.head)

<bound method NDFrame.head of         Ano      Mês  Código do Produto  Código de Barras  \
0    2023.0  04/2023       7.895155e+12      7.895155e+12
1    2023.0  04/2023       7.896359e+12      7.896359e+12
2    2023.0  04/2023       7.897292e+12      7.897292e+12
3    2023.0  04/2023       7.897698e+12      7.897698e+12
4    2023.0  04/2023       7.896359e+12      7.896359e+12
..      ...      ...                ...               ...
974  2023.0  04/2023       7.897292e+12      7.897292e+12
975  2023.0  04/2023       7.909875e+12      7.909875e+12
976  2023.0  04/2023       7.898944e+12      7.898944e+12
977  2023.0  04/2023       7.898944e+12      7.898944e+12
978     NaN      NaN                NaN               NaN

                            Descrição do Produto  Quantidade   Valor Bruto  \
0           Separador Organizador Plast Vd Menta         1.0         25,00
1      Pote Com Travas Plast Sanremo 1,6L SR1742         1.0         24,75
2               Porta Talheres Giplas Sort Ta-01        16.0        140,00
3           Caixa Organizadora 10l Ret M C/ Abas         2.0        107,00
4    Porta Escova de Dentes Sanremo Plástico 687         2.0         15,00
..                                           ...         ...           ...
974        Pote 600ml Giplas Red Alto Sort Pm-06        18.0         40,50
975                  Acucareiros Plast Capuccino         1.0         16,50
976         Cesto Organizador Br 30x21x7cm Linea         1.0         30,00
977       Organizador Diamond 15x15x15cm Cristal         1.0         49,25
978                                          NaN      4845.0  R$ 70.205,50

    Valor Desconto Valor Líquido Valor Vale Troca Líquido - Troca  \
0             0,00         25,00             0,00           25,00
1             0,00         24,75             0,00           24,75
2             0,00        140,00             0,00          140,00
3             0,00        107,00             0,00          107,00
4             0,00         15,00             0,00           15,00
..             ...           ...              ...             ...
974           0,00         40,50             0,00           40,50
975           0,00         16,50             0,00           16,50
976           0,00         30,00             0,00           30,00
977           0,00         49,25             0,00           49,25
978    R$ 1.927,93  R$ 68.277,57        R$ 297,21    R$ 67.980,36

     Estoque Atual  Estoque Mínimo
0              0.0             0.0
1              0.0             0.0
2              0.0             0.0
3              0.0             0.0
4              0.0             0.0
..             ...             ...
974            0.0             0.0
975            0.0             0.0
976            0.0             0.0
977            0.0             0.0
978            NaN             NaN

[979 rows x 13 columns]>

In [46]:
df = pd.read_csv('convertido.csv')
colunas = df.drop(columns={'Líquido - Troca', 'Estoque Atual', 'Estoque Mínimo'}, axis=1)
colunas.to_csv('convertido.csv', index=False)
colunas

,Ano,Mês,Código do Produto,Código de Barras,Descrição do Produto,Quantidade,Valor Bruto,Valor Desconto,Valor Líquido,Valor Vale Troca
0,2023.0,04/2023,7.895155e+12,7.895155e+12,Separador Organizador Plast Vd Menta,1.0,"25,00","0,00","25,00","0,00"
1,2023.0,04/2023,7.896359e+12,7.896359e+12,"Pote Com Travas Plast Sanremo 1,6L SR1742",1.0,"24,75","0,00","24,75","0,00"
2,2023.0,04/2023,7.897292e+12,7.897292e+12,Porta Talheres Giplas Sort Ta-01,16.0,"140,00","0,00","140,00","0,00"
3,2023.0,04/2023,7.897698e+12,7.897698e+12,Caixa Organizadora 10l Ret M C/ Abas,2.0,"107,00","0,00","107,00","0,00"
4,2023.0,04/2023,7.896359e+12,7.896359e+12,Porta Escova de Dentes Sanremo Plástico 687,2.0,"15,00","0,00","15,00","0,00"
...,...,...,...,...,...,...,...,...,...,...
974,2023.0,04/2023,7.897292e+12,7.897292e+12,Pote 600ml Giplas Red Alto Sort Pm-06,18.0,"40,50","0,00","40,50","0,00"
975,2023.0,04/2023,7.909875e+12,7.909875e+12,Acucareiros Plast Capuccino,1.0,"16,50","0,00","16,50","0,00"
976,2023.0,04/2023,7.898944e+12,7.898944e+12,Cesto Organizador Br 30x21x7cm Linea,1.0,"30,00","0,00","30,00","0,00"
977,2023.0,04/2023,7.898944e+12,7.898944e+12,Organizador Diamond 15x15x15cm Cristal,1.0,"49,25","0,00","49,25","0,00"
978,NaN,NaN,NaN,NaN,NaN,4845.0,"R$ 70.205,50","R$ 1.927,93","R$ 68.277,57","R$ 297,21"